In [1]:
import torch
import random
from torch.utils import data

In [2]:
def gen(data):
    n = len(data)
    n_samples = len(data)
    for _ in range(n_samples//n):
        for v in torch.randperm(n).tolist():
            yield v
    for v in torch.randperm(n).tolist()[:n_samples%n]:
        yield v

In [3]:
def gen_gen(data):
    n = len(data)
    n_samples = len(data)
    generator = torch.Generator()
    for _ in range(n_samples//n):
        yield from torch.randperm(n, generator=generator).tolist()
    yield from torch.randperm(n, generator=generator).tolist()[:n_samples%n]

In [10]:
def b_gen(batch_size, sample):
    batch = [0]*batch_size
    idx_batch = 0
    for idx in sample:
        batch[idx_batch] = idx
        idx_batch += 1
        if idx_batch == batch_size:
            yield batch
            idx_batch = 0
            batch = [0]*batch_size
    if idx_batch > 0:
        yield batch[:idx_batch]

In [19]:
print(torch.randperm(10))
print(torch.randint(high=10,size=(32,)))

tensor([1, 7, 5, 8, 2, 4, 3, 0, 6, 9])
tensor([9, 9, 0, 2, 7, 4, 8, 6, 1, 0, 7, 2, 0, 8, 9, 8, 4, 7, 1, 4, 6, 2, 9, 7,
        5, 8, 4, 4, 2, 8, 4, 1])


In [16]:
idx = list(gen(range(10)))
print(idx)
[g for g in b_gen(2, idx)]

[5, 4, 3, 0, 6, 7, 2, 9, 8, 1]


[[5, 4], [3, 0], [6, 7], [2, 9], [8, 1]]

In [21]:
data = list()
data.append([1,2,3,4,5])
data.append([6,7,8,9,10])
data.append([11,12,13,14])

In [31]:
data = list()
data.append([[1,2,3],[2,3,4]])
data.append([[1,2,3],[4,5,6]])
data.append([[1,2,3],[5,6,7]])
t = torch.tensor(data, dtype=torch.int32)

In [32]:
t.shape

torch.Size([3, 2, 3])

In [29]:
torch.max(t, 1).values

tensor([[2, 3, 4],
        [4, 5, 6],
        [5, 6, 7]])

In [33]:
torch.max_pool1d(t, 1)

RuntimeError: "max_pool1d_impl" not implemented for 'Int'

In [35]:
embedding = torch.nn.Embedding(10, 3)

In [37]:
embedding.weight

Parameter containing:
tensor([[ 0.1469,  0.7656, -0.0039],
        [ 1.0852, -1.0769, -1.1379],
        [-0.3497, -0.1153,  0.7755],
        [-2.2621, -1.6181,  0.2361],
        [-0.2531, -0.9481, -1.0242],
        [ 0.0071,  0.0684, -2.3986],
        [-0.9717,  0.0388, -1.0730],
        [ 0.7681, -1.1504,  1.0806],
        [ 0.2182, -0.3881, -1.2451],
        [-0.2465, -0.2583, -0.0700]], requires_grad=True)

In [42]:
embedding(torch.tensor([10]))

IndexError: index out of range in self

In [ ]:
a = tensor()